// English sidebar for libreforge & EcoEnchants docs.
// grouped by path prefix.
// Extracted verbatim from docs/.vitepress/config.ts (order and content preserved).
import type { DefaultTheme } from "vitepress";

const guideGroup: DefaultTheme.SidebarItem = {
  text: "Guide",
  items: [
    { text: "Overview", link: "/guide/" },
    { text: "Effect Basics", link: "/guide/effect-basics" },
    {
      text: "EcoEnchants Specific",
      link: "/guide/ecoenchants-specific",
    },
    { text: "Glossary", link: "/glossary" },
  ],
};

export const enSidebar: DefaultTheme.Sidebar = {
  '/guide/': [guideGroup],
  '/glossary': [guideGroup],
  '/effects/': [
    {
      text: "Effects",
      items: [
        { text: "All Effects (Landing)", link: "/effects/" },
        { text: "activate_pet", link: "/effects/activate_pet" },
        { text: "add_damage", link: "/effects/add_damage" },
        { text: "add_durability", link: "/effects/add_durability" },
        { text: "add_enchant", link: "/effects/add_enchant" },
        { text: "add_global_points", link: "/effects/add_global_points" },
        { text: "add_holder", link: "/effects/add_holder" },
        {
          text: "add_holder_in_radius",
          link: "/effects/add_holder_in_radius",
        },
        {
          text: "add_holder_to_victim",
          link: "/effects/add_holder_to_victim",
        },
        { text: "add_luck", link: "/effects/add_luck" },
        {
          text: "add_permanent_holder_in_radius",
          link: "/effects/add_permanent_holder_in_radius",
        },
        { text: "add_points", link: "/effects/add_points" },
        { text: "add_stat", link: "/effects/add_stat" },
        {
          text: "add_stat_temporarily",
          link: "/effects/add_stat_temporarily",
        },
        { text: "age_crop", link: "/effects/age_crop" },
        { text: "all_players", link: "/effects/all_players" },
        { text: "animation", link: "/effects/animation" },
        {
          text: "antigravity_projectile",
          link: "/effects/antigravity_projectile",
        },
        { text: "aoe", link: "/effects/aoe" },
        { text: "aoe_blocks", link: "/effects/aoe_blocks" },
        {
          text: "apply_random_reforge",
          link: "/effects/apply_random_reforge",
        },
        { text: "apply_reforge", link: "/effects/apply_reforge" },
        { text: "armor", link: "/effects/armor" },
        { text: "armor_toughness", link: "/effects/armor_toughness" },
        { text: "arrow_ring", link: "/effects/arrow_ring" },
        { text: "arrow_storm", link: "/effects/arrow_storm" },
        {
          text: "attack_speed_multiplier",
          link: "/effects/attack_speed_multiplier",
        },
        { text: "autosmelt", link: "/effects/autosmelt" },
        {
          text: "battlepass_task_xp_multiplier",
          link: "/effects/battlepass_task_xp_multiplier",
        },
        {
          text: "battlepass_xp_multiplier",
          link: "/effects/battlepass_xp_multiplier",
        },
        { text: "bleed", link: "/effects/bleed" },
        { text: "blink", link: "/effects/blink" },
        { text: "block_commands", link: "/effects/block_commands" },
        { text: "block_reach", link: "/effects/block_reach" },
        { text: "bonus_health", link: "/effects/bonus_health" },
        { text: "break_block", link: "/effects/break_block" },
        {
          text: "brew_time_multiplier",
          link: "/effects/brew_time_multiplier",
        },
        { text: "broadcast", link: "/effects/broadcast" },
        {
          text: "burning_time_multiplier",
          link: "/effects/burning_time_multiplier",
        },
        { text: "cancel_event", link: "/effects/cancel_event" },
        { text: "cast_mythic_skill", link: "/effects/cast_mythic_skill" },
        { text: "chain_lightning", link: "/effects/chain_lightning" },
        { text: "clear_inventory", link: "/effects/clear_inventory" },
        {
          text: "clear_invulnerability",
          link: "/effects/clear_invulnerability",
        },
        { text: "close_inventory", link: "/effects/close_inventory" },
        { text: "consume_held_item", link: "/effects/consume_held_item" },
        { text: "copy_item", link: "/effects/copy_item" },
        { text: "create_boss_bar", link: "/effects/create_boss_bar" },
        { text: "create_explosion", link: "/effects/create_explosion" },
        { text: "create_hologram", link: "/effects/create_hologram" },
        { text: "crit_multiplier", link: "/effects/crit_multiplier" },
        { text: "damage_armor", link: "/effects/damage_armor" },
        { text: "damage_item", link: "/effects/damage_item" },
        { text: "damage_mainhand", link: "/effects/damage_mainhand" },
        { text: "damage_multiplier", link: "/effects/damage_multiplier" },
        {
          text: "damage_nearby_entities",
          link: "/effects/damage_nearby_entities",
        },
        { text: "damage_offhand", link: "/effects/damage_offhand" },
        { text: "damage_twice", link: "/effects/damage_twice" },
        { text: "damage_victim", link: "/effects/damage_victim" },
        { text: "deactivate_pet", link: "/effects/deactivate_pet" },
        {
          text: "dont_consume_lapis_chance",
          link: "/effects/dont_consume_lapis_chance",
        },
        {
          text: "dont_consume_xp_chance",
          link: "/effects/dont_consume_xp_chance",
        },
        { text: "drill", link: "/effects/drill" },
        { text: "drop_item", link: "/effects/drop_item" },
        { text: "drop_item_slot", link: "/effects/drop_item_slot" },
        { text: "drop_pickup_item", link: "/effects/drop_pickup_item" },
        { text: "drop_random_item", link: "/effects/drop_random_item" },
        {
          text: "drop_weighted_random_item",
          link: "/effects/drop_weighted_random_item",
        },
        { text: "drop_xp", link: "/effects/drop_xp" },
        {
          text: "elytra_boost_save_chance",
          link: "/effects/elytra_boost_save_chance",
        },
        { text: "entity_reach", link: "/effects/entity_reach" },
        {
          text: "explosion_knockback_resistance_multiplier",
          link: "/effects/explosion_knockback_resistance_multiplier",
        },
        { text: "extinguish", link: "/effects/extinguish" },
        { text: "feather_step", link: "/effects/feather_step" },
        { text: "firework", link: "/effects/firework" },
        { text: "flight", link: "/effects/flight" },
        { text: "food_multiplier", link: "/effects/food_multiplier" },
        { text: "frost_nova", link: "/effects/frost_nova" },
        { text: "gain_task_xp", link: "/effects/gain_task_xp" },
        { text: "give_absorption", link: "/effects/give_absorption" },
        {
          text: "give_battlepass_task_xp",
          link: "/effects/give_battlepass_task_xp",
        },
        {
          text: "give_battlepass_tier",
          link: "/effects/give_battlepass_tier",
        },
        {
          text: "give_battlepass_xp",
          link: "/effects/give_battlepass_xp",
        },
        {
          text: "give_collection_count",
          link: "/effects/give_collection_count",
        },
        {
          text: "give_edprison_economy",
          link: "/effects/give_edprison_economy",
        },
        {
          text: "give_edprison_pouch",
          link: "/effects/give_edprison_pouch",
        },
        { text: "give_food", link: "/effects/give_food" },
        {
          text: "give_global_points",
          link: "/effects/give_global_points",
        },
        { text: "give_health", link: "/effects/give_health" },
        { text: "give_item", link: "/effects/give_item" },
        { text: "give_item_points", link: "/effects/give_item_points" },
        { text: "give_job_xp", link: "/effects/give_job_xp" },
        {
          text: "give_lands_balance",
          link: "/effects/give_lands_balance",
        },
        { text: "give_magic", link: "/effects/give_magic" },
        { text: "give_mcmmo_xp", link: "/effects/give_mcmmo_xp" },
        { text: "give_mob_coins", link: "/effects/give_mob_coins" },
        { text: "give_money", link: "/effects/give_money" },
        { text: "give_oxygen", link: "/effects/give_oxygen" },
        { text: "give_permission", link: "/effects/give_permission" },
        { text: "give_pet_xp", link: "/effects/give_pet_xp" },
        { text: "give_points", link: "/effects/give_points" },
        { text: "give_price", link: "/effects/give_price" },
        { text: "give_saturation", link: "/effects/give_saturation" },
        { text: "give_skill_xp", link: "/effects/give_skill_xp" },
        {
          text: "give_skill_xp_naturally",
          link: "/effects/give_skill_xp_naturally",
        },
        { text: "give_task_xp", link: "/effects/give_task_xp" },
        { text: "give_xp", link: "/effects/give_xp" },
        {
          text: "glow_nearby_blocks",
          link: "/effects/glow_nearby_blocks",
        },
        {
          text: "gravity_multiplier",
          link: "/effects/gravity_multiplier",
        },
        { text: "harvest_crop", link: "/effects/harvest_crop" },
        { text: "homing", link: "/effects/homing" },
        { text: "hunger_multiplier", link: "/effects/hunger_multiplier" },
        { text: "ignite", link: "/effects/ignite" },
        {
          text: "increase_step_height",
          link: "/effects/increase_step_height",
        },
        { text: "inscribe_item", link: "/effects/inscribe_item" },
        {
          text: "item_durability_multiplier",
          link: "/effects/item_durability_multiplier",
        },
        { text: "job_xp_multiplier", link: "/effects/job_xp_multiplier" },
        {
          text: "jobs_money_multiplier",
          link: "/effects/jobs_money_multiplier",
        },
        {
          text: "jobs_xp_multiplier",
          link: "/effects/jobs_xp_multiplier",
        },
        {
          text: "jump_strength_multiplier",
          link: "/effects/jump_strength_multiplier",
        },
        { text: "keep_inventory", link: "/effects/keep_inventory" },
        { text: "keep_level", link: "/effects/keep_level" },
        { text: "kick", link: "/effects/kick" },
        { text: "kill", link: "/effects/kill" },
        { text: "knock_away", link: "/effects/knock_away" },
        {
          text: "knockback_multiplier",
          link: "/effects/knockback_multiplier",
        },
        {
          text: "knockback_resistance_multiplier",
          link: "/effects/knockback_resistance_multiplier",
        },
        { text: "level_item", link: "/effects/level_item" },
        { text: "lifesteal", link: "/effects/lifesteal" },
        {
          text: "magic_regen_multiplier",
          link: "/effects/magic_regen_multiplier",
        },
        { text: "make_skill_crit", link: "/effects/make_skill_crit" },
        {
          text: "mcmmo_xp_multiplier",
          link: "/effects/mcmmo_xp_multiplier",
        },
        { text: "mine_radius", link: "/effects/mine_radius" },
        {
          text: "mine_radius_one_deep",
          link: "/effects/mine_radius_one_deep",
        },
        { text: "mine_vein", link: "/effects/mine_vein" },
        { text: "mining_efficiency", link: "/effects/mining_efficiency" },
        {
          text: "mining_speed_multiplier",
          link: "/effects/mining_speed_multiplier",
        },
        {
          text: "mob_coins_chance_multiplier",
          link: "/effects/mob_coins_chance_multiplier",
        },
        {
          text: "mob_coins_drop_multiplier",
          link: "/effects/mob_coins_drop_multiplier",
        },
        {
          text: "mob_coins_multiplier",
          link: "/effects/mob_coins_multiplier",
        },
        {
          text: "movement_efficiency_multiplier",
          link: "/effects/movement_efficiency_multiplier",
        },
        {
          text: "movement_speed_multiplier",
          link: "/effects/movement_speed_multiplier",
        },
        {
          text: "multiply_all_stats",
          link: "/effects/multiply_all_stats",
        },
        { text: "multiply_drops", link: "/effects/multiply_drops" },
        {
          text: "multiply_edprison_economy",
          link: "/effects/multiply_edprison_economy",
        },
        {
          text: "multiply_global_points",
          link: "/effects/multiply_global_points",
        },
        {
          text: "multiply_item_points",
          link: "/effects/multiply_item_points",
        },
        { text: "multiply_magic", link: "/effects/multiply_magic" },
        { text: "multiply_points", link: "/effects/multiply_points" },
        { text: "multiply_stat", link: "/effects/multiply_stat" },
        {
          text: "multiply_stat_temporarily",
          link: "/effects/multiply_stat_temporarily",
        },
        { text: "multiply_velocity", link: "/effects/multiply_velocity" },
        { text: "name_entity", link: "/effects/name_entity" },
        { text: "open_crafting", link: "/effects/open_crafting" },
        { text: "open_ender_chest", link: "/effects/open_ender_chest" },
        { text: "open_menu", link: "/effects/open_menu" },
        { text: "oxygen_bonus", link: "/effects/oxygen_bonus" },
        {
          text: "particle_animation",
          link: "/effects/particle_animation",
        },
        { text: "particle_line", link: "/effects/particle_line" },
        { text: "pay_price", link: "/effects/pay_price" },
        {
          text: "permanent_potion_effect",
          link: "/effects/permanent_potion_effect",
        },
        { text: "pet_xp_multiplier", link: "/effects/pet_xp_multiplier" },
        { text: "piercing", link: "/effects/piercing" },
        { text: "place_block", link: "/effects/place_block" },
        { text: "play_animation", link: "/effects/play_animation" },
        { text: "play_sound", link: "/effects/play_sound" },
        {
          text: "potion_duration_multiplier",
          link: "/effects/potion_duration_multiplier",
        },
        { text: "potion_effect", link: "/effects/potion_effect" },
        { text: "pull_in", link: "/effects/pull_in" },
        { text: "pull_to_location", link: "/effects/pull_to_location" },
        {
          text: "quest_xp_multiplier",
          link: "/effects/quest_xp_multiplier",
        },
        { text: "random_player", link: "/effects/random_player" },
        { text: "random_teleport", link: "/effects/random_teleport" },
        { text: "rapid_bows", link: "/effects/rapid_bows" },
        {
          text: "reel_speed_multiplier",
          link: "/effects/reel_speed_multiplier",
        },
        { text: "reflect", link: "/effects/reflect" },
        { text: "regen_multiplier", link: "/effects/regen_multiplier" },
        { text: "remove_boss_bar", link: "/effects/remove_boss_bar" },
        { text: "remove_dispatcher", link: "/effects/remove_dispatcher" },
        { text: "remove_enchant", link: "/effects/remove_enchant" },
        { text: "remove_item", link: "/effects/remove_item" },
        { text: "remove_item_data", link: "/effects/remove_item_data" },
        {
          text: "remove_potion_effect",
          link: "/effects/remove_potion_effect",
        },
        { text: "remove_reforge", link: "/effects/remove_reforge" },
        { text: "remove_victim", link: "/effects/remove_victim" },
        { text: "repair_item", link: "/effects/repair_item" },
        { text: "replace_near", link: "/effects/replace_near" },
        { text: "replant_crops", link: "/effects/replant_crops" },
        {
          text: "reset_previous_menu",
          link: "/effects/reset_previous_menu",
        },
        { text: "rotate", link: "/effects/rotate" },
        { text: "rotate_victim", link: "/effects/rotate_victim" },
        { text: "run_chain", link: "/effects/run_chain" },
        { text: "run_command", link: "/effects/run_command" },
        {
          text: "run_player_command",
          link: "/effects/run_player_command",
        },
        {
          text: "safe_fall_distance",
          link: "/effects/safe_fall_distance",
        },
        { text: "scale", link: "/effects/scale" },
        { text: "sell_items", link: "/effects/sell_items" },
        { text: "sell_multiplier", link: "/effects/sell_multiplier" },
        {
          text: "send_discord_webhook",
          link: "/effects/send_discord_webhook",
        },
        { text: "send_message", link: "/effects/send_message" },
        { text: "send_minimessage", link: "/effects/send_minimessage" },
        { text: "send_title", link: "/effects/send_title" },
        { text: "set_armor_trim", link: "/effects/set_armor_trim" },
        {
          text: "set_battlepass_tier",
          link: "/effects/set_battlepass_tier",
        },
        { text: "set_block", link: "/effects/set_block" },
        {
          text: "set_custom_model_data",
          link: "/effects/set_custom_model_data",
        },
        {
          text: "set_edprison_economy",
          link: "/effects/set_edprison_economy",
        },
        { text: "set_food", link: "/effects/set_food" },
        { text: "set_freeze_ticks", link: "/effects/set_freeze_ticks" },
        { text: "set_global_points", link: "/effects/set_global_points" },
        { text: "set_glowing", link: "/effects/set_glowing" },
        { text: "set_item_data", link: "/effects/set_item_data" },
        { text: "set_item_points", link: "/effects/set_item_points" },
        { text: "set_lands_balance", link: "/effects/set_lands_balance" },
        { text: "set_points", link: "/effects/set_points" },
        { text: "set_saturation", link: "/effects/set_saturation" },
        { text: "set_unbreakable", link: "/effects/set_unbreakable" },
        { text: "set_velocity", link: "/effects/set_velocity" },
        {
          text: "set_victim_velocity",
          link: "/effects/set_victim_velocity",
        },
        { text: "shockwave", link: "/effects/shockwave" },
        { text: "shoot", link: "/effects/shoot" },
        { text: "shoot_arrow", link: "/effects/shoot_arrow" },
        { text: "shoot_firework", link: "/effects/shoot_firework" },
        { text: "shuffle_hotbar", link: "/effects/shuffle_hotbar" },
        { text: "silence", link: "/effects/silence" },
        {
          text: "skill_xp_multiplier",
          link: "/effects/skill_xp_multiplier",
        },
        { text: "smite", link: "/effects/smite" },
        {
          text: "sneaking_speed_multiplier",
          link: "/effects/sneaking_speed_multiplier",
        },
        { text: "sort_inventory", link: "/effects/sort_inventory" },
        { text: "soul_rip", link: "/effects/soul_rip" },
        { text: "spawn_entity", link: "/effects/spawn_entity" },
        { text: "spawn_mobs", link: "/effects/spawn_mobs" },
        { text: "spawn_particle", link: "/effects/spawn_particle" },
        {
          text: "spawn_potion_cloud",
          link: "/effects/spawn_potion_cloud",
        },
        { text: "start_quest", link: "/effects/start_quest" },
        { text: "strike_lightning", link: "/effects/strike_lightning" },
        { text: "strip_ai", link: "/effects/strip_ai" },
        { text: "stun", link: "/effects/stun" },
        { text: "swap_positions", link: "/effects/swap_positions" },
        { text: "swarm", link: "/effects/swarm" },
        { text: "take_mob_coins", link: "/effects/take_mob_coins" },
        { text: "take_money", link: "/effects/take_money" },
        { text: "target_player", link: "/effects/target_player" },
        { text: "telekinesis", link: "/effects/telekinesis" },
        { text: "teleport", link: "/effects/teleport" },
        { text: "teleport_to", link: "/effects/teleport_to" },
        {
          text: "teleport_to_ground",
          link: "/effects/teleport_to_ground",
        },
        { text: "time_bomb", link: "/effects/time_bomb" },
        {
          text: "total_damage_multiplier",
          link: "/effects/total_damage_multiplier",
        },
        { text: "traceback", link: "/effects/traceback" },
        { text: "transmission", link: "/effects/transmission" },
        { text: "trigger_custom", link: "/effects/trigger_custom" },
        {
          text: "underwater_mining_speed_multiplier",
          link: "/effects/underwater_mining_speed_multiplier",
        },
        { text: "uninscribe_item", link: "/effects/uninscribe_item" },
        { text: "unlock_collection", link: "/effects/unlock_collection" },
        { text: "update_boss_bar", link: "/effects/update_boss_bar" },
        {
          text: "update_edprison_pickaxe",
          link: "/effects/update_edprison_pickaxe",
        },
        {
          text: "victim_speed_multiplier",
          link: "/effects/victim_speed_multiplier",
        },
        {
          text: "villager_trade_multiplier",
          link: "/effects/villager_trade_multiplier",
        },
        { text: "vortex", link: "/effects/vortex" },
        {
          text: "water_movement_efficiency_multiplier",
          link: "/effects/water_movement_efficiency_multiplier",
        },
        { text: "xp_multiplier", link: "/effects/xp_multiplier" },
      ],
    },
  ],
  '/triggers/': [
    {
      text: "Triggers",
      items: [
        { text: "All Triggers (Landing)", link: "/triggers/" },
        { text: "alt_click", link: "/triggers/alt_click" },
        { text: "anvil_modify", link: "/triggers/anvil_modify" },
        { text: "beacon_effect", link: "/triggers/beacon_effect" },
        { text: "bite", link: "/triggers/bite" },
        { text: "blank", link: "/triggers/blank" },
        { text: "block_item_drop", link: "/triggers/block_item_drop" },
        { text: "block_xp_drop", link: "/triggers/block_xp_drop" },
        { text: "bonemeal_crop", link: "/triggers/bonemeal_crop" },
        { text: "bow_attack", link: "/triggers/bow_attack" },
        { text: "breed", link: "/triggers/breed" },
        { text: "brew", link: "/triggers/brew" },
        { text: "brew_ingredient", link: "/triggers/brew_ingredient" },
        { text: "cast_rod", link: "/triggers/cast_rod" },
        { text: "catch_entity", link: "/triggers/catch_entity" },
        { text: "catch_fish", link: "/triggers/catch_fish" },
        { text: "catch_fish_fail", link: "/triggers/catch_fish_fail" },
        {
          text: "cauldron_level_change",
          link: "/triggers/cauldron_level_change",
        },
        { text: "change_armor", link: "/triggers/change_armor" },
        { text: "change_biome", link: "/triggers/change_biome" },
        { text: "change_chunk", link: "/triggers/change_chunk" },
        { text: "change_world", link: "/triggers/change_world" },
        { text: "click_block", link: "/triggers/click_block" },
        { text: "click_entity", link: "/triggers/click_entity" },
        {
          text: "collide_with_entity",
          link: "/triggers/collide_with_entity",
        },
        {
          text: "complete_advancement",
          link: "/triggers/complete_advancement",
        },
        { text: "compost_item", link: "/triggers/compost_item" },
        { text: "consume", link: "/triggers/consume" },
        { text: "craft", link: "/triggers/craft" },
        { text: "damage_item", link: "/triggers/damage_item" },
        { text: "death", link: "/triggers/death" },
        { text: "deploy_elytra", link: "/triggers/deploy_elytra" },
        { text: "disable", link: "/triggers/disable" },
        { text: "drink", link: "/triggers/drink" },
        { text: "drop_item", link: "/triggers/drop_item" },
        { text: "elytra_boost", link: "/triggers/elytra_boost" },
        { text: "empty_bucket", link: "/triggers/empty_bucket" },
        { text: "enable", link: "/triggers/enable" },
        { text: "enchant_item", link: "/triggers/enchant_item" },
        { text: "enter_bed", link: "/triggers/enter_bed" },
        { text: "enter_vehicle", link: "/triggers/enter_vehicle" },
        {
          text: "entity_break_door",
          link: "/triggers/entity_break_door",
        },
        {
          text: "entity_catch_fire_from_block",
          link: "/triggers/entity_catch_fire_from_block",
        },
        {
          text: "entity_catch_fire_from_entity",
          link: "/triggers/entity_catch_fire_from_entity",
        },
        { text: "entity_damage", link: "/triggers/entity_damage" },
        {
          text: "entity_damage_by_entity",
          link: "/triggers/entity_damage_by_entity",
        },
        { text: "entity_death", link: "/triggers/entity_death" },
        { text: "entity_item_drop", link: "/triggers/entity_item_drop" },
        { text: "entity_spawn", link: "/triggers/entity_spawn" },
        { text: "entity_target", link: "/triggers/entity_target" },
        { text: "entity_teleport", link: "/triggers/entity_teleport" },
        { text: "entity_xp_drop", link: "/triggers/entity_xp_drop" },
        { text: "exit_vehicle", link: "/triggers/exit_vehicle" },
        { text: "fall_damage", link: "/triggers/fall_damage" },
        { text: "fill_bucket", link: "/triggers/fill_bucket" },
        { text: "gain_hunger", link: "/triggers/gain_hunger" },
        { text: "gain_xp", link: "/triggers/gain_xp" },
        { text: "grind_item", link: "/triggers/grind_item" },
        { text: "headshot", link: "/triggers/headshot" },
        { text: "heal", link: "/triggers/heal" },
        { text: "hold_item", link: "/triggers/hold_item" },
        { text: "hook_in_ground", link: "/triggers/hook_in_ground" },
        { text: "item_break", link: "/triggers/item_break" },
        { text: "join", link: "/triggers/join" },
        { text: "jump", link: "/triggers/jump" },
        { text: "kill", link: "/triggers/kill" },
        { text: "leash_entity", link: "/triggers/leash_entity" },
        { text: "leave", link: "/triggers/leave" },
        { text: "leave_bed", link: "/triggers/leave_bed" },
        { text: "leave_land", link: "/triggers/leave_land" },
        { text: "level_up_item", link: "/triggers/level_up_item" },
        { text: "level_up_xp", link: "/triggers/level_up_xp" },
        { text: "lose_hunger", link: "/triggers/lose_hunger" },
        {
          text: "lose_potion_effect",
          link: "/triggers/lose_potion_effect",
        },
        { text: "melee_attack", link: "/triggers/melee_attack" },
        { text: "mine_block", link: "/triggers/mine_block" },
        {
          text: "mine_block_cascade",
          link: "/triggers/mine_block_cascade",
        },
        {
          text: "mine_block_progress",
          link: "/triggers/mine_block_progress",
        },
        { text: "move", link: "/triggers/move" },
        { text: "move_item", link: "/triggers/move_item" },
        { text: "note_block_play", link: "/triggers/note_block_play" },
        { text: "pick_up_item", link: "/triggers/pick_up_item" },
        { text: "place_block", link: "/triggers/place_block" },
        { text: "potion_effect", link: "/triggers/potion_effect" },
        { text: "projectile_hit", link: "/triggers/projectile_hit" },
        {
          text: "projectile_launch",
          link: "/triggers/projectile_launch",
        },
        { text: "reel_in", link: "/triggers/reel_in" },
        { text: "rename_entity", link: "/triggers/rename_entity" },
        { text: "respawn", link: "/triggers/respawn" },
        { text: "resurrect", link: "/triggers/resurrect" },
        { text: "ring_bell", link: "/triggers/ring_bell" },
        { text: "run_command", link: "/triggers/run_command" },
        { text: "sell_item", link: "/triggers/sell_item" },
        { text: "send_message", link: "/triggers/send_message" },
        { text: "shear_entity", link: "/triggers/shear_entity" },
        { text: "shear", link: "/triggers/shear" },
        { text: "shield_block", link: "/triggers/shield_block" },
        { text: "shoot_bow", link: "/triggers/shoot_bow" },
        { text: "smelt", link: "/triggers/smelt" },
        { text: "smith_item", link: "/triggers/smith_item" },
        { text: "start_swimming", link: "/triggers/start_swimming" },
        { text: "swap_hands", link: "/triggers/swap_hands" },
        { text: "swing", link: "/triggers/swing" },
        { text: "take_damage", link: "/triggers/take_damage" },
        {
          text: "take_entity_damage",
          link: "/triggers/take_entity_damage",
        },
        { text: "tame_animal", link: "/triggers/tame_animal" },
        { text: "teleport", link: "/triggers/teleport" },
        { text: "toggle_flight", link: "/triggers/toggle_flight" },
        { text: "toggle_sneak", link: "/triggers/toggle_sneak" },
        { text: "toggle_sprint", link: "/triggers/toggle_sprint" },
        { text: "trident_attack", link: "/triggers/trident_attack" },
        { text: "trident_hit", link: "/triggers/trident_hit" },
        { text: "unleash_entity", link: "/triggers/unleash_entity" },
        { text: "use_flower_pot", link: "/triggers/use_flower_pot" },
        { text: "villager_trade", link: "/triggers/villager_trade" },
        { text: "win_raid", link: "/triggers/win_raid" },
        {
          text: "claim_battlepass_reward",
          link: "/triggers/claim_battlepass_reward",
        },
        {
          text: "complete_battlepass_task",
          link: "/triggers/complete_battlepass_task",
        },
        {
          text: "gain_battlepass_xp",
          link: "/triggers/gain_battlepass_xp",
        },
        {
          text: "tier_up_battlepass",
          link: "/triggers/tier_up_battlepass",
        },
        {
          text: "complete_collection",
          link: "/triggers/complete_collection",
        },
        {
          text: "tier_up_collection",
          link: "/triggers/tier_up_collection",
        },
        {
          text: "unlock_collection",
          link: "/triggers/unlock_collection",
        },
        { text: "enchant_type", link: "/triggers/enchant_type" },
        { text: "advance_armor", link: "/triggers/advance_armor" },
        {
          text: "upgrade_armor_tier",
          link: "/triggers/upgrade_armor_tier",
        },
        { text: "gain_job_xp", link: "/triggers/gain_job_xp" },
        { text: "join_job", link: "/triggers/join_job" },
        { text: "leave_job", link: "/triggers/leave_job" },
        { text: "level_up_job", link: "/triggers/level_up_job" },
        { text: "gain_pet_xp", link: "/triggers/gain_pet_xp" },
        { text: "level_up_pet", link: "/triggers/level_up_pet" },
        { text: "pet_activate", link: "/triggers/pet_activate" },
        { text: "pet_deactivate", link: "/triggers/pet_deactivate" },
        { text: "complete_quest", link: "/triggers/complete_quest" },
        { text: "complete_task", link: "/triggers/complete_task" },
        { text: "gain_task_xp", link: "/triggers/gain_task_xp" },
        { text: "start_quest", link: "/triggers/start_quest" },
        { text: "inscribe", link: "/triggers/inscribe" },
        { text: "try_inscribe", link: "/triggers/try_inscribe" },
        { text: "buy_item", link: "/triggers/buy_item" },
        { text: "gain_skill_xp", link: "/triggers/gain_skill_xp" },
        { text: "level_up_skill", link: "/triggers/level_up_skill" },
        { text: "regen_magic", link: "/triggers/regen_magic" },
        { text: "reforge_item", link: "/triggers/reforge_item" },
        { text: "collect_envoy", link: "/triggers/collect_envoy" },
        { text: "player_trade", link: "/triggers/player_trade" },
        { text: "left_click_npc", link: "/triggers/left_click_npc" },
        { text: "right_click_npc", link: "/triggers/right_click_npc" },
        {
          text: "harvest_custom_crop",
          link: "/triggers/harvest_custom_crop",
        },
        {
          text: "plant_custom_crop",
          link: "/triggers/plant_custom_crop",
        },
        { text: "use_fertilizer", link: "/triggers/use_fertilizer" },
        { text: "use_watering_can", link: "/triggers/use_watering_can" },
        { text: "change_town_role", link: "/triggers/change_town_role" },
        { text: "create_town", link: "/triggers/create_town" },
        { text: "disband_town", link: "/triggers/disband_town" },
        { text: "join_town", link: "/triggers/join_town" },
        { text: "leave_town", link: "/triggers/leave_town" },
        { text: "enter_claim", link: "/triggers/enter_claim" },
        { text: "claim", link: "/triggers/claim" },
        { text: "exit_claim", link: "/triggers/exit_claim" },
        { text: "unclaim", link: "/triggers/unclaim" },
        { text: "jobs_level_up", link: "/triggers/jobs_level_up" },
        { text: "join_land", link: "/triggers/join_land" },
        {
          text: "lands_bank_deposit",
          link: "/triggers/lands_bank_deposit",
        },
        {
          text: "lands_bank_withdraw",
          link: "/triggers/lands_bank_withdraw",
        },
        {
          text: "lands_spawn_teleport",
          link: "/triggers/lands_spawn_teleport",
        },
        { text: "gain_mcmmo_xp", link: "/triggers/gain_mcmmo_xp" },
        { text: "level_down_mcmmo", link: "/triggers/level_down_mcmmo" },
        { text: "level_up_mcmmo", link: "/triggers/level_up_mcmmo" },
        {
          text: "mcmmo_ability_activate",
          link: "/triggers/mcmmo_ability_activate",
        },
        {
          text: "mcmmo_ability_deactivate",
          link: "/triggers/mcmmo_ability_deactivate",
        },
        {
          text: "take_mythic_damage",
          link: "/triggers/take_mythic_damage",
        },
        {
          text: "scyther_auto_collect",
          link: "/triggers/scyther_auto_collect",
        },
        {
          text: "scyther_auto_sell",
          link: "/triggers/scyther_auto_sell",
        },
        { text: "register_vote", link: "/triggers/register_vote" },
        { text: "pyro_catch_fish", link: "/triggers/pyro_catch_fish" },
        { text: "enter_region", link: "/triggers/enter_region" },
        { text: "leave_region", link: "/triggers/leave_region" },
      ],
    },
  ],
  '/conditions/': [
    {
      text: "Conditions",
      items: [
        { text: "All Conditions (Landing)", link: "/conditions/" },
        { text: "above_balance", link: "/conditions/above_balance" },
        {
          text: "above_global_points",
          link: "/conditions/above_global_points",
        },
        {
          text: "above_health_percent",
          link: "/conditions/above_health_percent",
        },
        {
          text: "above_hunger_percent",
          link: "/conditions/above_hunger_percent",
        },
        { text: "above_magic", link: "/conditions/above_magic" },
        { text: "above_points", link: "/conditions/above_points" },
        { text: "above_xp_level", link: "/conditions/above_xp_level" },
        { text: "above_y", link: "/conditions/above_y" },
        { text: "any_of", link: "/conditions/any_of" },
        { text: "at_least_of", link: "/conditions/at_least_of" },
        { text: "below_balance", link: "/conditions/below_balance" },
        {
          text: "below_global_points",
          link: "/conditions/below_global_points",
        },
        {
          text: "below_health_percent",
          link: "/conditions/below_health_percent",
        },
        {
          text: "below_hunger_percent",
          link: "/conditions/below_hunger_percent",
        },
        { text: "below_magic", link: "/conditions/below_magic" },
        { text: "below_points", link: "/conditions/below_points" },
        { text: "below_xp_level", link: "/conditions/below_xp_level" },
        { text: "below_y", link: "/conditions/below_y" },
        {
          text: "can_afford_price",
          link: "/conditions/can_afford_price",
        },
        {
          text: "collection_complete",
          link: "/conditions/collection_complete",
        },
        {
          text: "collection_tier_at_least",
          link: "/conditions/collection_tier_at_least",
        },
        {
          text: "collection_unlocked",
          link: "/conditions/collection_unlocked",
        },
        {
          text: "global_points_equal",
          link: "/conditions/global_points_equal",
        },
        { text: "has_active_job", link: "/conditions/has_active_job" },
        { text: "has_active_pet", link: "/conditions/has_active_pet" },
        {
          text: "has_battlepass_tier",
          link: "/conditions/has_battlepass_tier",
        },
        {
          text: "has_boss_bar_visible",
          link: "/conditions/has_boss_bar_visible",
        },
        {
          text: "has_completed_advancement",
          link: "/conditions/has_completed_advancement",
        },
        {
          text: "has_completed_quest",
          link: "/conditions/has_completed_quest",
        },
        {
          text: "has_completed_task",
          link: "/conditions/has_completed_task",
        },
        { text: "has_ecoitem", link: "/conditions/has_ecoitem" },
        {
          text: "has_edprison_currency",
          link: "/conditions/has_edprison_currency",
        },
        {
          text: "has_edprison_robot",
          link: "/conditions/has_edprison_robot",
        },
        { text: "has_enchant", link: "/conditions/has_enchant" },
        { text: "has_item", link: "/conditions/has_item" },
        { text: "has_item_data", link: "/conditions/has_item_data" },
        { text: "has_job_level", link: "/conditions/has_job_level" },
        { text: "has_lands_role", link: "/conditions/has_lands_role" },
        { text: "has_mana", link: "/conditions/has_mana" },
        { text: "has_mcmmo_level", link: "/conditions/has_mcmmo_level" },
        { text: "has_permission", link: "/conditions/has_permission" },
        { text: "has_pet", link: "/conditions/has_pet" },
        { text: "has_pet_level", link: "/conditions/has_pet_level" },
        {
          text: "has_potion_effect",
          link: "/conditions/has_potion_effect",
        },
        {
          text: "has_premium_battlepass",
          link: "/conditions/has_premium_battlepass",
        },
        {
          text: "has_quest_active",
          link: "/conditions/has_quest_active",
        },
        { text: "has_reforge", link: "/conditions/has_reforge" },
        {
          text: "has_scoreboard_visible",
          link: "/conditions/has_scoreboard_visible",
        },
        { text: "has_scroll", link: "/conditions/has_scroll" },
        { text: "has_skill_level", link: "/conditions/has_skill_level" },
        { text: "has_talisman", link: "/conditions/has_talisman" },
        { text: "has_town_role", link: "/conditions/has_town_role" },
        { text: "in_air", link: "/conditions/in_air" },
        { text: "in_biome", link: "/conditions/in_biome" },
        { text: "in_block", link: "/conditions/in_block" },
        { text: "in_bubble", link: "/conditions/in_bubble" },
        {
          text: "in_edprison_gang",
          link: "/conditions/in_edprison_gang",
        },
        { text: "in_gamemode", link: "/conditions/in_gamemode" },
        { text: "in_lava", link: "/conditions/in_lava" },
        { text: "in_mainhand", link: "/conditions/in_mainhand" },
        { text: "in_offhand", link: "/conditions/in_offhand" },
        { text: "in_own_claim", link: "/conditions/in_own_claim" },
        { text: "in_rain", link: "/conditions/in_rain" },
        { text: "in_region", link: "/conditions/in_region" },
        { text: "in_slot", link: "/conditions/in_slot" },
        {
          text: "in_trusted_claim",
          link: "/conditions/in_trusted_claim",
        },
        { text: "in_water", link: "/conditions/in_water" },
        { text: "in_world", link: "/conditions/in_world" },
        { text: "is_alive", link: "/conditions/is_alive" },
        {
          text: "is_booster_active",
          link: "/conditions/is_booster_active",
        },
        {
          text: "is_expression_true",
          link: "/conditions/is_expression_true",
        },
        { text: "is_falling", link: "/conditions/is_falling" },
        { text: "is_flying", link: "/conditions/is_flying" },
        { text: "is_frozen", link: "/conditions/is_frozen" },
        { text: "is_gliding", link: "/conditions/is_gliding" },
        { text: "is_night", link: "/conditions/is_night" },
        { text: "is_op", link: "/conditions/is_op" },
        { text: "is_season", link: "/conditions/is_season" },
        { text: "is_sneaking", link: "/conditions/is_sneaking" },
        { text: "is_sprinting", link: "/conditions/is_sprinting" },
        { text: "is_storm", link: "/conditions/is_storm" },
        { text: "is_submerged", link: "/conditions/is_submerged" },
        { text: "is_swimming", link: "/conditions/is_swimming" },
        { text: "is_wearing_set", link: "/conditions/is_wearing_set" },
        {
          text: "item_data_equals",
          link: "/conditions/item_data_equals",
        },
        {
          text: "item_level_above",
          link: "/conditions/item_level_above",
        },
        {
          text: "item_level_below",
          link: "/conditions/item_level_below",
        },
        {
          text: "item_level_equals",
          link: "/conditions/item_level_equals",
        },
        {
          text: "item_points_above",
          link: "/conditions/item_points_above",
        },
        {
          text: "item_points_below",
          link: "/conditions/item_points_below",
        },
        {
          text: "item_points_equal",
          link: "/conditions/item_points_equal",
        },
        {
          text: "lands_balance_above",
          link: "/conditions/lands_balance_above",
        },
        {
          text: "lands_balance_below",
          link: "/conditions/lands_balance_below",
        },
        {
          text: "lands_balance_equal",
          link: "/conditions/lands_balance_equal",
        },
        {
          text: "light_level_below",
          link: "/conditions/light_level_below",
        },
        {
          text: "mcmmo_ability_on_cooldown",
          link: "/conditions/mcmmo_ability_on_cooldown",
        },
        { text: "near_entity", link: "/conditions/near_entity" },
        { text: "on_fire", link: "/conditions/on_fire" },
        { text: "on_ground", link: "/conditions/on_ground" },
        {
          text: "placeholder_contains",
          link: "/conditions/placeholder_contains",
        },
        {
          text: "placeholder_equals",
          link: "/conditions/placeholder_equals",
        },
        {
          text: "placeholder_greater_than",
          link: "/conditions/placeholder_greater_than",
        },
        {
          text: "placeholder_less_than",
          link: "/conditions/placeholder_less_than",
        },
        { text: "points_equal", link: "/conditions/points_equal" },
        { text: "riding_entity", link: "/conditions/riding_entity" },
        {
          text: "standing_on_block",
          link: "/conditions/standing_on_block",
        },
        { text: "stat_above", link: "/conditions/stat_above" },
        { text: "stat_below", link: "/conditions/stat_below" },
        { text: "stat_equals", link: "/conditions/stat_equals" },
        { text: "wearing_boots", link: "/conditions/wearing_boots" },
        {
          text: "wearing_chestplate",
          link: "/conditions/wearing_chestplate",
        },
        { text: "wearing_helmet", link: "/conditions/wearing_helmet" },
        {
          text: "wearing_leggings",
          link: "/conditions/wearing_leggings",
        },
        {
          text: "within_radius_of",
          link: "/conditions/within_radius_of",
        },
      ],
    },
  ],
  '/mutators/': [
    {
      text: "Mutators",
      items: [
        { text: "All Mutators (Landing)", link: "/mutators/" },
        {
          text: "block_to_location",
          link: "/mutators/block_to_location",
        },
        {
          text: "dispatcher_as_player",
          link: "/mutators/dispatcher_as_player",
        },
        {
          text: "dispatcher_as_victim",
          link: "/mutators/dispatcher_as_victim",
        },
        {
          text: "location_to_block",
          link: "/mutators/location_to_block",
        },
        {
          text: "location_to_cursor",
          link: "/mutators/location_to_cursor",
        },
        { text: "location_to_drop", link: "/mutators/location_to_drop" },
        {
          text: "location_to_player",
          link: "/mutators/location_to_player",
        },
        {
          text: "location_to_projectile",
          link: "/mutators/location_to_projectile",
        },
        {
          text: "location_to_victim",
          link: "/mutators/location_to_victim",
        },
        { text: "player_as_victim", link: "/mutators/player_as_victim" },
        { text: "player_to_pet", link: "/mutators/player_to_pet" },
        { text: "spin_location", link: "/mutators/spin_location" },
        { text: "spin_velocity", link: "/mutators/spin_velocity" },
        {
          text: "translate_location",
          link: "/mutators/translate_location",
        },
        {
          text: "victim_as_dispatcher",
          link: "/mutators/victim_as_dispatcher",
        },
        { text: "victim_as_player", link: "/mutators/victim_as_player" },
        { text: "victim_to_owner", link: "/mutators/victim_to_owner" },
      ],
    },
  ],
  '/examples/': [
    {
      text: "Examples",
      items: [{ text: "Examples & Best Practices", link: "/examples/" }],
    },
  ],
};
