// Chinese sidebar for libreforge & EcoEnchants docs.
// 按路径前缀分组.
// Extracted verbatim from docs/.vitepress/config.ts (order and content preserved).
import type { DefaultTheme } from "vitepress";

const zhGuideGroup: DefaultTheme.SidebarItem = {
  text: "指南",
  items: [
    { text: "总览", link: "/zh/guide/" },
    { text: "Effect 基础", link: "/zh/guide/effect-basics" },
    {
      text: "EcoEnchants 专属",
      link: "/zh/guide/ecoenchants-specific",
    },
    { text: "术语表", link: "/zh/glossary" },
  ],
};

export const zhSidebar: DefaultTheme.Sidebar = {
  '/zh/guide/': [zhGuideGroup],
  '/zh/glossary': [zhGuideGroup],
  '/zh/effects/': [
    {
      text: "Effects 效果",
      items: [
        { text: "所有效果（导航页）", link: "/zh/effects/" },
        { text: "activate_pet", link: "/zh/effects/activate_pet" },
        { text: "add_damage", link: "/zh/effects/add_damage" },
        { text: "add_durability", link: "/zh/effects/add_durability" },
        { text: "add_enchant", link: "/zh/effects/add_enchant" },
        {
          text: "add_global_points",
          link: "/zh/effects/add_global_points",
        },
        { text: "add_holder", link: "/zh/effects/add_holder" },
        {
          text: "add_holder_in_radius",
          link: "/zh/effects/add_holder_in_radius",
        },
        {
          text: "add_holder_to_victim",
          link: "/zh/effects/add_holder_to_victim",
        },
        { text: "add_luck", link: "/zh/effects/add_luck" },
        {
          text: "add_permanent_holder_in_radius",
          link: "/zh/effects/add_permanent_holder_in_radius",
        },
        { text: "add_points", link: "/zh/effects/add_points" },
        { text: "add_stat", link: "/zh/effects/add_stat" },
        {
          text: "add_stat_temporarily",
          link: "/zh/effects/add_stat_temporarily",
        },
        { text: "age_crop", link: "/zh/effects/age_crop" },
        { text: "all_players", link: "/zh/effects/all_players" },
        { text: "animation", link: "/zh/effects/animation" },
        {
          text: "antigravity_projectile",
          link: "/zh/effects/antigravity_projectile",
        },
        { text: "aoe", link: "/zh/effects/aoe" },
        { text: "aoe_blocks", link: "/zh/effects/aoe_blocks" },
        {
          text: "apply_random_reforge",
          link: "/zh/effects/apply_random_reforge",
        },
        { text: "apply_reforge", link: "/zh/effects/apply_reforge" },
        { text: "armor", link: "/zh/effects/armor" },
        { text: "armor_toughness", link: "/zh/effects/armor_toughness" },
        { text: "arrow_ring", link: "/zh/effects/arrow_ring" },
        { text: "arrow_storm", link: "/zh/effects/arrow_storm" },
        {
          text: "attack_speed_multiplier",
          link: "/zh/effects/attack_speed_multiplier",
        },
        { text: "autosmelt", link: "/zh/effects/autosmelt" },
        {
          text: "battlepass_task_xp_multiplier",
          link: "/zh/effects/battlepass_task_xp_multiplier",
        },
        {
          text: "battlepass_xp_multiplier",
          link: "/zh/effects/battlepass_xp_multiplier",
        },
        { text: "bleed", link: "/zh/effects/bleed" },
        { text: "blink", link: "/zh/effects/blink" },
        { text: "block_commands", link: "/zh/effects/block_commands" },
        { text: "block_reach", link: "/zh/effects/block_reach" },
        { text: "bonus_health", link: "/zh/effects/bonus_health" },
        { text: "break_block", link: "/zh/effects/break_block" },
        {
          text: "brew_time_multiplier",
          link: "/zh/effects/brew_time_multiplier",
        },
        { text: "broadcast", link: "/zh/effects/broadcast" },
        {
          text: "burning_time_multiplier",
          link: "/zh/effects/burning_time_multiplier",
        },
        { text: "cancel_event", link: "/zh/effects/cancel_event" },
        {
          text: "cast_mythic_skill",
          link: "/zh/effects/cast_mythic_skill",
        },
        { text: "chain_lightning", link: "/zh/effects/chain_lightning" },
        { text: "clear_inventory", link: "/zh/effects/clear_inventory" },
        {
          text: "clear_invulnerability",
          link: "/zh/effects/clear_invulnerability",
        },
        { text: "close_inventory", link: "/zh/effects/close_inventory" },
        {
          text: "consume_held_item",
          link: "/zh/effects/consume_held_item",
        },
        { text: "copy_item", link: "/zh/effects/copy_item" },
        { text: "create_boss_bar", link: "/zh/effects/create_boss_bar" },
        {
          text: "create_explosion",
          link: "/zh/effects/create_explosion",
        },
        { text: "create_hologram", link: "/zh/effects/create_hologram" },
        { text: "crit_multiplier", link: "/zh/effects/crit_multiplier" },
        { text: "damage_armor", link: "/zh/effects/damage_armor" },
        { text: "damage_item", link: "/zh/effects/damage_item" },
        { text: "damage_mainhand", link: "/zh/effects/damage_mainhand" },
        {
          text: "damage_multiplier",
          link: "/zh/effects/damage_multiplier",
        },
        {
          text: "damage_nearby_entities",
          link: "/zh/effects/damage_nearby_entities",
        },
        { text: "damage_offhand", link: "/zh/effects/damage_offhand" },
        { text: "damage_twice", link: "/zh/effects/damage_twice" },
        { text: "damage_victim", link: "/zh/effects/damage_victim" },
        { text: "deactivate_pet", link: "/zh/effects/deactivate_pet" },
        {
          text: "dont_consume_lapis_chance",
          link: "/zh/effects/dont_consume_lapis_chance",
        },
        {
          text: "dont_consume_xp_chance",
          link: "/zh/effects/dont_consume_xp_chance",
        },
        { text: "drill", link: "/zh/effects/drill" },
        { text: "drop_item", link: "/zh/effects/drop_item" },
        { text: "drop_item_slot", link: "/zh/effects/drop_item_slot" },
        {
          text: "drop_pickup_item",
          link: "/zh/effects/drop_pickup_item",
        },
        {
          text: "drop_random_item",
          link: "/zh/effects/drop_random_item",
        },
        {
          text: "drop_weighted_random_item",
          link: "/zh/effects/drop_weighted_random_item",
        },
        { text: "drop_xp", link: "/zh/effects/drop_xp" },
        {
          text: "elytra_boost_save_chance",
          link: "/zh/effects/elytra_boost_save_chance",
        },
        { text: "entity_reach", link: "/zh/effects/entity_reach" },
        {
          text: "explosion_knockback_resistance_multiplier",
          link: "/zh/effects/explosion_knockback_resistance_multiplier",
        },
        { text: "extinguish", link: "/zh/effects/extinguish" },
        { text: "feather_step", link: "/zh/effects/feather_step" },
        { text: "firework", link: "/zh/effects/firework" },
        { text: "flight", link: "/zh/effects/flight" },
        { text: "food_multiplier", link: "/zh/effects/food_multiplier" },
        { text: "frost_nova", link: "/zh/effects/frost_nova" },
        { text: "gain_task_xp", link: "/zh/effects/gain_task_xp" },
        { text: "give_absorption", link: "/zh/effects/give_absorption" },
        {
          text: "give_battlepass_task_xp",
          link: "/zh/effects/give_battlepass_task_xp",
        },
        {
          text: "give_battlepass_tier",
          link: "/zh/effects/give_battlepass_tier",
        },
        {
          text: "give_battlepass_xp",
          link: "/zh/effects/give_battlepass_xp",
        },
        {
          text: "give_collection_count",
          link: "/zh/effects/give_collection_count",
        },
        {
          text: "give_edprison_economy",
          link: "/zh/effects/give_edprison_economy",
        },
        {
          text: "give_edprison_pouch",
          link: "/zh/effects/give_edprison_pouch",
        },
        { text: "give_food", link: "/zh/effects/give_food" },
        {
          text: "give_global_points",
          link: "/zh/effects/give_global_points",
        },
        { text: "give_health", link: "/zh/effects/give_health" },
        { text: "give_item", link: "/zh/effects/give_item" },
        {
          text: "give_item_points",
          link: "/zh/effects/give_item_points",
        },
        { text: "give_job_xp", link: "/zh/effects/give_job_xp" },
        {
          text: "give_lands_balance",
          link: "/zh/effects/give_lands_balance",
        },
        { text: "give_magic", link: "/zh/effects/give_magic" },
        { text: "give_mcmmo_xp", link: "/zh/effects/give_mcmmo_xp" },
        { text: "give_mob_coins", link: "/zh/effects/give_mob_coins" },
        { text: "give_money", link: "/zh/effects/give_money" },
        { text: "give_oxygen", link: "/zh/effects/give_oxygen" },
        { text: "give_permission", link: "/zh/effects/give_permission" },
        { text: "give_pet_xp", link: "/zh/effects/give_pet_xp" },
        { text: "give_points", link: "/zh/effects/give_points" },
        { text: "give_price", link: "/zh/effects/give_price" },
        { text: "give_saturation", link: "/zh/effects/give_saturation" },
        { text: "give_skill_xp", link: "/zh/effects/give_skill_xp" },
        {
          text: "give_skill_xp_naturally",
          link: "/zh/effects/give_skill_xp_naturally",
        },
        { text: "give_task_xp", link: "/zh/effects/give_task_xp" },
        { text: "give_xp", link: "/zh/effects/give_xp" },
        {
          text: "glow_nearby_blocks",
          link: "/zh/effects/glow_nearby_blocks",
        },
        {
          text: "gravity_multiplier",
          link: "/zh/effects/gravity_multiplier",
        },
        { text: "harvest_crop", link: "/zh/effects/harvest_crop" },
        { text: "homing", link: "/zh/effects/homing" },
        {
          text: "hunger_multiplier",
          link: "/zh/effects/hunger_multiplier",
        },
        { text: "ignite", link: "/zh/effects/ignite" },
        {
          text: "increase_step_height",
          link: "/zh/effects/increase_step_height",
        },
        { text: "inscribe_item", link: "/zh/effects/inscribe_item" },
        {
          text: "item_durability_multiplier",
          link: "/zh/effects/item_durability_multiplier",
        },
        {
          text: "job_xp_multiplier",
          link: "/zh/effects/job_xp_multiplier",
        },
        {
          text: "jobs_money_multiplier",
          link: "/zh/effects/jobs_money_multiplier",
        },
        {
          text: "jobs_xp_multiplier",
          link: "/zh/effects/jobs_xp_multiplier",
        },
        {
          text: "jump_strength_multiplier",
          link: "/zh/effects/jump_strength_multiplier",
        },
        { text: "keep_inventory", link: "/zh/effects/keep_inventory" },
        { text: "keep_level", link: "/zh/effects/keep_level" },
        { text: "kick", link: "/zh/effects/kick" },
        { text: "kill", link: "/zh/effects/kill" },
        { text: "knock_away", link: "/zh/effects/knock_away" },
        {
          text: "knockback_multiplier",
          link: "/zh/effects/knockback_multiplier",
        },
        {
          text: "knockback_resistance_multiplier",
          link: "/zh/effects/knockback_resistance_multiplier",
        },
        { text: "level_item", link: "/zh/effects/level_item" },
        { text: "lifesteal", link: "/zh/effects/lifesteal" },
        {
          text: "magic_regen_multiplier",
          link: "/zh/effects/magic_regen_multiplier",
        },
        { text: "make_skill_crit", link: "/zh/effects/make_skill_crit" },
        {
          text: "mcmmo_xp_multiplier",
          link: "/zh/effects/mcmmo_xp_multiplier",
        },
        { text: "mine_radius", link: "/zh/effects/mine_radius" },
        {
          text: "mine_radius_one_deep",
          link: "/zh/effects/mine_radius_one_deep",
        },
        { text: "mine_vein", link: "/zh/effects/mine_vein" },
        {
          text: "mining_efficiency",
          link: "/zh/effects/mining_efficiency",
        },
        {
          text: "mining_speed_multiplier",
          link: "/zh/effects/mining_speed_multiplier",
        },
        {
          text: "mob_coins_chance_multiplier",
          link: "/zh/effects/mob_coins_chance_multiplier",
        },
        {
          text: "mob_coins_drop_multiplier",
          link: "/zh/effects/mob_coins_drop_multiplier",
        },
        {
          text: "mob_coins_multiplier",
          link: "/zh/effects/mob_coins_multiplier",
        },
        {
          text: "movement_efficiency_multiplier",
          link: "/zh/effects/movement_efficiency_multiplier",
        },
        {
          text: "movement_speed_multiplier",
          link: "/zh/effects/movement_speed_multiplier",
        },
        {
          text: "multiply_all_stats",
          link: "/zh/effects/multiply_all_stats",
        },
        { text: "multiply_drops", link: "/zh/effects/multiply_drops" },
        {
          text: "multiply_edprison_economy",
          link: "/zh/effects/multiply_edprison_economy",
        },
        {
          text: "multiply_global_points",
          link: "/zh/effects/multiply_global_points",
        },
        {
          text: "multiply_item_points",
          link: "/zh/effects/multiply_item_points",
        },
        { text: "multiply_magic", link: "/zh/effects/multiply_magic" },
        { text: "multiply_points", link: "/zh/effects/multiply_points" },
        { text: "multiply_stat", link: "/zh/effects/multiply_stat" },
        {
          text: "multiply_stat_temporarily",
          link: "/zh/effects/multiply_stat_temporarily",
        },
        {
          text: "multiply_velocity",
          link: "/zh/effects/multiply_velocity",
        },
        { text: "name_entity", link: "/zh/effects/name_entity" },
        { text: "open_crafting", link: "/zh/effects/open_crafting" },
        {
          text: "open_ender_chest",
          link: "/zh/effects/open_ender_chest",
        },
        { text: "open_menu", link: "/zh/effects/open_menu" },
        { text: "oxygen_bonus", link: "/zh/effects/oxygen_bonus" },
        {
          text: "particle_animation",
          link: "/zh/effects/particle_animation",
        },
        { text: "particle_line", link: "/zh/effects/particle_line" },
        { text: "pay_price", link: "/zh/effects/pay_price" },
        {
          text: "permanent_potion_effect",
          link: "/zh/effects/permanent_potion_effect",
        },
        {
          text: "pet_xp_multiplier",
          link: "/zh/effects/pet_xp_multiplier",
        },
        { text: "piercing", link: "/zh/effects/piercing" },
        { text: "place_block", link: "/zh/effects/place_block" },
        { text: "play_animation", link: "/zh/effects/play_animation" },
        { text: "play_sound", link: "/zh/effects/play_sound" },
        {
          text: "potion_duration_multiplier",
          link: "/zh/effects/potion_duration_multiplier",
        },
        { text: "potion_effect", link: "/zh/effects/potion_effect" },
        { text: "pull_in", link: "/zh/effects/pull_in" },
        {
          text: "pull_to_location",
          link: "/zh/effects/pull_to_location",
        },
        {
          text: "quest_xp_multiplier",
          link: "/zh/effects/quest_xp_multiplier",
        },
        { text: "random_player", link: "/zh/effects/random_player" },
        { text: "random_teleport", link: "/zh/effects/random_teleport" },
        { text: "rapid_bows", link: "/zh/effects/rapid_bows" },
        {
          text: "reel_speed_multiplier",
          link: "/zh/effects/reel_speed_multiplier",
        },
        { text: "reflect", link: "/zh/effects/reflect" },
        {
          text: "regen_multiplier",
          link: "/zh/effects/regen_multiplier",
        },
        { text: "remove_boss_bar", link: "/zh/effects/remove_boss_bar" },
        {
          text: "remove_dispatcher",
          link: "/zh/effects/remove_dispatcher",
        },
        { text: "remove_enchant", link: "/zh/effects/remove_enchant" },
        { text: "remove_item", link: "/zh/effects/remove_item" },
        {
          text: "remove_item_data",
          link: "/zh/effects/remove_item_data",
        },
        {
          text: "remove_potion_effect",
          link: "/zh/effects/remove_potion_effect",
        },
        { text: "remove_reforge", link: "/zh/effects/remove_reforge" },
        { text: "remove_victim", link: "/zh/effects/remove_victim" },
        { text: "repair_item", link: "/zh/effects/repair_item" },
        { text: "replace_near", link: "/zh/effects/replace_near" },
        { text: "replant_crops", link: "/zh/effects/replant_crops" },
        {
          text: "reset_previous_menu",
          link: "/zh/effects/reset_previous_menu",
        },
        { text: "rotate", link: "/zh/effects/rotate" },
        { text: "rotate_victim", link: "/zh/effects/rotate_victim" },
        { text: "run_chain", link: "/zh/effects/run_chain" },
        { text: "run_command", link: "/zh/effects/run_command" },
        {
          text: "run_player_command",
          link: "/zh/effects/run_player_command",
        },
        {
          text: "safe_fall_distance",
          link: "/zh/effects/safe_fall_distance",
        },
        { text: "scale", link: "/zh/effects/scale" },
        { text: "sell_items", link: "/zh/effects/sell_items" },
        { text: "sell_multiplier", link: "/zh/effects/sell_multiplier" },
        {
          text: "send_discord_webhook",
          link: "/zh/effects/send_discord_webhook",
        },
        { text: "send_message", link: "/zh/effects/send_message" },
        {
          text: "send_minimessage",
          link: "/zh/effects/send_minimessage",
        },
        { text: "send_title", link: "/zh/effects/send_title" },
        { text: "set_armor_trim", link: "/zh/effects/set_armor_trim" },
        {
          text: "set_battlepass_tier",
          link: "/zh/effects/set_battlepass_tier",
        },
        { text: "set_block", link: "/zh/effects/set_block" },
        {
          text: "set_custom_model_data",
          link: "/zh/effects/set_custom_model_data",
        },
        {
          text: "set_edprison_economy",
          link: "/zh/effects/set_edprison_economy",
        },
        { text: "set_food", link: "/zh/effects/set_food" },
        {
          text: "set_freeze_ticks",
          link: "/zh/effects/set_freeze_ticks",
        },
        {
          text: "set_global_points",
          link: "/zh/effects/set_global_points",
        },
        { text: "set_glowing", link: "/zh/effects/set_glowing" },
        { text: "set_item_data", link: "/zh/effects/set_item_data" },
        { text: "set_item_points", link: "/zh/effects/set_item_points" },
        {
          text: "set_lands_balance",
          link: "/zh/effects/set_lands_balance",
        },
        { text: "set_points", link: "/zh/effects/set_points" },
        { text: "set_saturation", link: "/zh/effects/set_saturation" },
        { text: "set_unbreakable", link: "/zh/effects/set_unbreakable" },
        { text: "set_velocity", link: "/zh/effects/set_velocity" },
        {
          text: "set_victim_velocity",
          link: "/zh/effects/set_victim_velocity",
        },
        { text: "shockwave", link: "/zh/effects/shockwave" },
        { text: "shoot", link: "/zh/effects/shoot" },
        { text: "shoot_arrow", link: "/zh/effects/shoot_arrow" },
        { text: "shoot_firework", link: "/zh/effects/shoot_firework" },
        { text: "shuffle_hotbar", link: "/zh/effects/shuffle_hotbar" },
        { text: "silence", link: "/zh/effects/silence" },
        {
          text: "skill_xp_multiplier",
          link: "/zh/effects/skill_xp_multiplier",
        },
        { text: "smite", link: "/zh/effects/smite" },
        {
          text: "sneaking_speed_multiplier",
          link: "/zh/effects/sneaking_speed_multiplier",
        },
        { text: "sort_inventory", link: "/zh/effects/sort_inventory" },
        { text: "soul_rip", link: "/zh/effects/soul_rip" },
        { text: "spawn_entity", link: "/zh/effects/spawn_entity" },
        { text: "spawn_mobs", link: "/zh/effects/spawn_mobs" },
        { text: "spawn_particle", link: "/zh/effects/spawn_particle" },
        {
          text: "spawn_potion_cloud",
          link: "/zh/effects/spawn_potion_cloud",
        },
        { text: "start_quest", link: "/zh/effects/start_quest" },
        {
          text: "strike_lightning",
          link: "/zh/effects/strike_lightning",
        },
        { text: "strip_ai", link: "/zh/effects/strip_ai" },
        { text: "stun", link: "/zh/effects/stun" },
        { text: "swap_positions", link: "/zh/effects/swap_positions" },
        { text: "swarm", link: "/zh/effects/swarm" },
        { text: "take_mob_coins", link: "/zh/effects/take_mob_coins" },
        { text: "take_money", link: "/zh/effects/take_money" },
        { text: "target_player", link: "/zh/effects/target_player" },
        { text: "telekinesis", link: "/zh/effects/telekinesis" },
        { text: "teleport", link: "/zh/effects/teleport" },
        { text: "teleport_to", link: "/zh/effects/teleport_to" },
        {
          text: "teleport_to_ground",
          link: "/zh/effects/teleport_to_ground",
        },
        { text: "time_bomb", link: "/zh/effects/time_bomb" },
        {
          text: "total_damage_multiplier",
          link: "/zh/effects/total_damage_multiplier",
        },
        { text: "traceback", link: "/zh/effects/traceback" },
        { text: "transmission", link: "/zh/effects/transmission" },
        { text: "trigger_custom", link: "/zh/effects/trigger_custom" },
        {
          text: "underwater_mining_speed_multiplier",
          link: "/zh/effects/underwater_mining_speed_multiplier",
        },
        { text: "uninscribe_item", link: "/zh/effects/uninscribe_item" },
        {
          text: "unlock_collection",
          link: "/zh/effects/unlock_collection",
        },
        { text: "update_boss_bar", link: "/zh/effects/update_boss_bar" },
        {
          text: "update_edprison_pickaxe",
          link: "/zh/effects/update_edprison_pickaxe",
        },
        {
          text: "victim_speed_multiplier",
          link: "/zh/effects/victim_speed_multiplier",
        },
        {
          text: "villager_trade_multiplier",
          link: "/zh/effects/villager_trade_multiplier",
        },
        { text: "vortex", link: "/zh/effects/vortex" },
        {
          text: "water_movement_efficiency_multiplier",
          link: "/zh/effects/water_movement_efficiency_multiplier",
        },
        { text: "xp_multiplier", link: "/zh/effects/xp_multiplier" },
      ],
    },
  ],
  '/zh/triggers/': [
    {
      text: "Triggers 触发器",
      items: [
        { text: "所有触发器（导航页）", link: "/zh/triggers/" },
        { text: "alt_click", link: "/zh/triggers/alt_click" },
        { text: "anvil_modify", link: "/zh/triggers/anvil_modify" },
        { text: "beacon_effect", link: "/zh/triggers/beacon_effect" },
        { text: "bite", link: "/zh/triggers/bite" },
        { text: "block_item_drop", link: "/zh/triggers/block_item_drop" },
        { text: "bonemeal_crop", link: "/zh/triggers/bonemeal_crop" },
        { text: "bow_attack", link: "/zh/triggers/bow_attack" },
        { text: "breed", link: "/zh/triggers/breed" },
        { text: "brew", link: "/zh/triggers/brew" },
        { text: "brew_ingredient", link: "/zh/triggers/brew_ingredient" },
        { text: "cast_rod", link: "/zh/triggers/cast_rod" },
        { text: "catch_entity", link: "/zh/triggers/catch_entity" },
        { text: "catch_fish", link: "/zh/triggers/catch_fish" },
        { text: "catch_fish_fail", link: "/zh/triggers/catch_fish_fail" },
        {
          text: "cauldron_level_change",
          link: "/zh/triggers/cauldron_level_change",
        },
        { text: "change_armor", link: "/zh/triggers/change_armor" },
        { text: "change_biome", link: "/zh/triggers/change_biome" },
        { text: "change_chunk", link: "/zh/triggers/change_chunk" },
        { text: "change_world", link: "/zh/triggers/change_world" },
        { text: "click_block", link: "/zh/triggers/click_block" },
        { text: "click_entity", link: "/zh/triggers/click_entity" },
        {
          text: "collide_with_entity",
          link: "/zh/triggers/collide_with_entity",
        },
        {
          text: "complete_advancement",
          link: "/zh/triggers/complete_advancement",
        },
        { text: "compost_item", link: "/zh/triggers/compost_item" },
        { text: "consume", link: "/zh/triggers/consume" },
        { text: "craft", link: "/zh/triggers/craft" },
        { text: "damage_item", link: "/zh/triggers/damage_item" },
        { text: "death", link: "/zh/triggers/death" },
        { text: "deploy_elytra", link: "/zh/triggers/deploy_elytra" },
        { text: "disable", link: "/zh/triggers/disable" },
        { text: "drop_item", link: "/zh/triggers/drop_item" },
        { text: "elytra_boost", link: "/zh/triggers/elytra_boost" },
        { text: "empty_bucket", link: "/zh/triggers/empty_bucket" },
        { text: "enable", link: "/zh/triggers/enable" },
        { text: "enchant_item", link: "/zh/triggers/enchant_item" },
        { text: "enter_bed", link: "/zh/triggers/enter_bed" },
        { text: "enter_vehicle", link: "/zh/triggers/enter_vehicle" },
        {
          text: "entity_break_door",
          link: "/zh/triggers/entity_break_door",
        },
        {
          text: "entity_catch_fire_from_block",
          link: "/zh/triggers/entity_catch_fire_from_block",
        },
        {
          text: "entity_catch_fire_from_entity",
          link: "/zh/triggers/entity_catch_fire_from_entity",
        },
        { text: "entity_damage", link: "/zh/triggers/entity_damage" },
        {
          text: "entity_damage_by_entity",
          link: "/zh/triggers/entity_damage_by_entity",
        },
        { text: "entity_death", link: "/zh/triggers/entity_death" },
        {
          text: "entity_item_drop",
          link: "/zh/triggers/entity_item_drop",
        },
        { text: "entity_spawn", link: "/zh/triggers/entity_spawn" },
        { text: "entity_target", link: "/zh/triggers/entity_target" },
        { text: "entity_teleport", link: "/zh/triggers/entity_teleport" },
        { text: "exit_vehicle", link: "/zh/triggers/exit_vehicle" },
        { text: "fall_damage", link: "/zh/triggers/fall_damage" },
        { text: "fill_bucket", link: "/zh/triggers/fill_bucket" },
        { text: "gain_hunger", link: "/zh/triggers/gain_hunger" },
        { text: "gain_xp", link: "/zh/triggers/gain_xp" },
        { text: "grind_item", link: "/zh/triggers/grind_item" },
        { text: "headshot", link: "/zh/triggers/headshot" },
        { text: "heal", link: "/zh/triggers/heal" },
        { text: "hold_item", link: "/zh/triggers/hold_item" },
        { text: "hook_in_ground", link: "/zh/triggers/hook_in_ground" },
        { text: "item_break", link: "/zh/triggers/item_break" },
        { text: "join", link: "/zh/triggers/join" },
        { text: "jump", link: "/zh/triggers/jump" },
        { text: "kill", link: "/zh/triggers/kill" },
        { text: "leash_entity", link: "/zh/triggers/leash_entity" },
        { text: "leave", link: "/zh/triggers/leave" },
        { text: "leave_bed", link: "/zh/triggers/leave_bed" },
        { text: "leave_land", link: "/zh/triggers/leave_land" },
        { text: "level_up_item", link: "/zh/triggers/level_up_item" },
        { text: "level_up_xp", link: "/zh/triggers/level_up_xp" },
        { text: "lose_hunger", link: "/zh/triggers/lose_hunger" },
        {
          text: "lose_potion_effect",
          link: "/zh/triggers/lose_potion_effect",
        },
        { text: "melee_attack", link: "/zh/triggers/melee_attack" },
        { text: "mine_block", link: "/zh/triggers/mine_block" },
        {
          text: "mine_block_cascade",
          link: "/zh/triggers/mine_block_cascade",
        },
        {
          text: "mine_block_progress",
          link: "/zh/triggers/mine_block_progress",
        },
        { text: "move", link: "/zh/triggers/move" },
        { text: "note_block_play", link: "/zh/triggers/note_block_play" },
        { text: "pick_up_item", link: "/zh/triggers/pick_up_item" },
        { text: "place_block", link: "/zh/triggers/place_block" },
        { text: "potion_effect", link: "/zh/triggers/potion_effect" },
        { text: "projectile_hit", link: "/zh/triggers/projectile_hit" },
        {
          text: "projectile_launch",
          link: "/zh/triggers/projectile_launch",
        },
        { text: "reel_in", link: "/zh/triggers/reel_in" },
        { text: "rename_entity", link: "/zh/triggers/rename_entity" },
        { text: "respawn", link: "/zh/triggers/respawn" },
        { text: "resurrect", link: "/zh/triggers/resurrect" },
        { text: "ring_bell", link: "/zh/triggers/ring_bell" },
        { text: "run_command", link: "/zh/triggers/run_command" },
        { text: "sell_item", link: "/zh/triggers/sell_item" },
        { text: "send_message", link: "/zh/triggers/send_message" },
        { text: "shear_entity", link: "/zh/triggers/shear_entity" },
        { text: "shield_block", link: "/zh/triggers/shield_block" },
        { text: "shoot_bow", link: "/zh/triggers/shoot_bow" },
        { text: "smelt", link: "/zh/triggers/smelt" },
        { text: "smith_item", link: "/zh/triggers/smith_item" },
        { text: "swap_hands", link: "/zh/triggers/swap_hands" },
        { text: "swing", link: "/zh/triggers/swing" },
        { text: "take_damage", link: "/zh/triggers/take_damage" },
        {
          text: "take_entity_damage",
          link: "/zh/triggers/take_entity_damage",
        },
        { text: "tame_animal", link: "/zh/triggers/tame_animal" },
        { text: "teleport", link: "/zh/triggers/teleport" },
        { text: "toggle_flight", link: "/zh/triggers/toggle_flight" },
        { text: "toggle_sneak", link: "/zh/triggers/toggle_sneak" },
        { text: "toggle_sprint", link: "/zh/triggers/toggle_sprint" },
        { text: "trident_attack", link: "/zh/triggers/trident_attack" },
        { text: "trident_hit", link: "/zh/triggers/trident_hit" },
        { text: "unleash_entity", link: "/zh/triggers/unleash_entity" },
        { text: "use_flower_pot", link: "/zh/triggers/use_flower_pot" },
        { text: "villager_trade", link: "/zh/triggers/villager_trade" },
        { text: "win_raid", link: "/zh/triggers/win_raid" },
        {
          text: "claim_battlepass_reward",
          link: "/zh/triggers/claim_battlepass_reward",
        },
        {
          text: "complete_battlepass_task",
          link: "/zh/triggers/complete_battlepass_task",
        },
        {
          text: "gain_battlepass_xp",
          link: "/zh/triggers/gain_battlepass_xp",
        },
        {
          text: "tier_up_battlepass",
          link: "/zh/triggers/tier_up_battlepass",
        },
        {
          text: "complete_collection",
          link: "/zh/triggers/complete_collection",
        },
        {
          text: "tier_up_collection",
          link: "/zh/triggers/tier_up_collection",
        },
        {
          text: "unlock_collection",
          link: "/zh/triggers/unlock_collection",
        },
        { text: "enchant_type", link: "/zh/triggers/enchant_type" },
        { text: "advance_armor", link: "/zh/triggers/advance_armor" },
        {
          text: "upgrade_armor_tier",
          link: "/zh/triggers/upgrade_armor_tier",
        },
        { text: "gain_job_xp", link: "/zh/triggers/gain_job_xp" },
        { text: "join_job", link: "/zh/triggers/join_job" },
        { text: "leave_job", link: "/zh/triggers/leave_job" },
        { text: "level_up_job", link: "/zh/triggers/level_up_job" },
        { text: "gain_pet_xp", link: "/zh/triggers/gain_pet_xp" },
        { text: "level_up_pet", link: "/zh/triggers/level_up_pet" },
        { text: "pet_activate", link: "/zh/triggers/pet_activate" },
        { text: "pet_deactivate", link: "/zh/triggers/pet_deactivate" },
        { text: "complete_quest", link: "/zh/triggers/complete_quest" },
        { text: "complete_task", link: "/zh/triggers/complete_task" },
        { text: "gain_task_xp", link: "/zh/triggers/gain_task_xp" },
        { text: "start_quest", link: "/zh/triggers/start_quest" },
        { text: "inscribe", link: "/zh/triggers/inscribe" },
        { text: "try_inscribe", link: "/zh/triggers/try_inscribe" },
        { text: "buy_item", link: "/zh/triggers/buy_item" },
        { text: "gain_skill_xp", link: "/zh/triggers/gain_skill_xp" },
        { text: "level_up_skill", link: "/zh/triggers/level_up_skill" },
        { text: "regen_magic", link: "/zh/triggers/regen_magic" },
        { text: "reforge_item", link: "/zh/triggers/reforge_item" },
        { text: "collect_envoy", link: "/zh/triggers/collect_envoy" },
        { text: "player_trade", link: "/zh/triggers/player_trade" },
        { text: "left_click_npc", link: "/zh/triggers/left_click_npc" },
        { text: "right_click_npc", link: "/zh/triggers/right_click_npc" },
        {
          text: "harvest_custom_crop",
          link: "/zh/triggers/harvest_custom_crop",
        },
        {
          text: "plant_custom_crop",
          link: "/zh/triggers/plant_custom_crop",
        },
        { text: "use_fertilizer", link: "/zh/triggers/use_fertilizer" },
        {
          text: "use_watering_can",
          link: "/zh/triggers/use_watering_can",
        },
        {
          text: "change_town_role",
          link: "/zh/triggers/change_town_role",
        },
        { text: "create_town", link: "/zh/triggers/create_town" },
        { text: "disband_town", link: "/zh/triggers/disband_town" },
        { text: "join_town", link: "/zh/triggers/join_town" },
        { text: "leave_town", link: "/zh/triggers/leave_town" },
        { text: "enter_claim", link: "/zh/triggers/enter_claim" },
        { text: "claim", link: "/zh/triggers/claim" },
        { text: "exit_claim", link: "/zh/triggers/exit_claim" },
        { text: "unclaim", link: "/zh/triggers/unclaim" },
        { text: "jobs_level_up", link: "/zh/triggers/jobs_level_up" },
        { text: "join_land", link: "/zh/triggers/join_land" },
        {
          text: "lands_bank_deposit",
          link: "/zh/triggers/lands_bank_deposit",
        },
        {
          text: "lands_bank_withdraw",
          link: "/zh/triggers/lands_bank_withdraw",
        },
        {
          text: "lands_spawn_teleport",
          link: "/zh/triggers/lands_spawn_teleport",
        },
        { text: "gain_mcmmo_xp", link: "/zh/triggers/gain_mcmmo_xp" },
        {
          text: "level_down_mcmmo",
          link: "/zh/triggers/level_down_mcmmo",
        },
        { text: "level_up_mcmmo", link: "/zh/triggers/level_up_mcmmo" },
        {
          text: "mcmmo_ability_activate",
          link: "/zh/triggers/mcmmo_ability_activate",
        },
        {
          text: "mcmmo_ability_deactivate",
          link: "/zh/triggers/mcmmo_ability_deactivate",
        },
        {
          text: "take_mythic_damage",
          link: "/zh/triggers/take_mythic_damage",
        },
        {
          text: "scyther_auto_collect",
          link: "/zh/triggers/scyther_auto_collect",
        },
        {
          text: "scyther_auto_sell",
          link: "/zh/triggers/scyther_auto_sell",
        },
        { text: "register_vote", link: "/zh/triggers/register_vote" },
        { text: "pyro_catch_fish", link: "/zh/triggers/pyro_catch_fish" },
        { text: "enter_region", link: "/zh/triggers/enter_region" },
        { text: "leave_region", link: "/zh/triggers/leave_region" },
      ],
    },
  ],
  '/zh/conditions/': [
    {
      text: "Conditions 条件",
      items: [
        { text: "所有条件（导航页）", link: "/zh/conditions/" },
        { text: "above_balance", link: "/zh/conditions/above_balance" },
        {
          text: "above_global_points",
          link: "/zh/conditions/above_global_points",
        },
        {
          text: "above_health_percent",
          link: "/zh/conditions/above_health_percent",
        },
        {
          text: "above_hunger_percent",
          link: "/zh/conditions/above_hunger_percent",
        },
        { text: "above_magic", link: "/zh/conditions/above_magic" },
        { text: "above_points", link: "/zh/conditions/above_points" },
        { text: "above_xp_level", link: "/zh/conditions/above_xp_level" },
        { text: "above_y", link: "/zh/conditions/above_y" },
        { text: "any_of", link: "/zh/conditions/any_of" },
        { text: "at_least_of", link: "/zh/conditions/at_least_of" },
        { text: "below_balance", link: "/zh/conditions/below_balance" },
        {
          text: "below_global_points",
          link: "/zh/conditions/below_global_points",
        },
        {
          text: "below_health_percent",
          link: "/zh/conditions/below_health_percent",
        },
        {
          text: "below_hunger_percent",
          link: "/zh/conditions/below_hunger_percent",
        },
        { text: "below_magic", link: "/zh/conditions/below_magic" },
        { text: "below_points", link: "/zh/conditions/below_points" },
        { text: "below_xp_level", link: "/zh/conditions/below_xp_level" },
        { text: "below_y", link: "/zh/conditions/below_y" },
        {
          text: "can_afford_price",
          link: "/zh/conditions/can_afford_price",
        },
        {
          text: "collection_complete",
          link: "/zh/conditions/collection_complete",
        },
        {
          text: "collection_tier_at_least",
          link: "/zh/conditions/collection_tier_at_least",
        },
        {
          text: "collection_unlocked",
          link: "/zh/conditions/collection_unlocked",
        },
        {
          text: "global_points_equal",
          link: "/zh/conditions/global_points_equal",
        },
        { text: "has_active_job", link: "/zh/conditions/has_active_job" },
        { text: "has_active_pet", link: "/zh/conditions/has_active_pet" },
        {
          text: "has_battlepass_tier",
          link: "/zh/conditions/has_battlepass_tier",
        },
        {
          text: "has_boss_bar_visible",
          link: "/zh/conditions/has_boss_bar_visible",
        },
        {
          text: "has_completed_advancement",
          link: "/zh/conditions/has_completed_advancement",
        },
        {
          text: "has_completed_quest",
          link: "/zh/conditions/has_completed_quest",
        },
        {
          text: "has_completed_task",
          link: "/zh/conditions/has_completed_task",
        },
        { text: "has_ecoitem", link: "/zh/conditions/has_ecoitem" },
        {
          text: "has_edprison_currency",
          link: "/zh/conditions/has_edprison_currency",
        },
        {
          text: "has_edprison_robot",
          link: "/zh/conditions/has_edprison_robot",
        },
        { text: "has_enchant", link: "/zh/conditions/has_enchant" },
        { text: "has_item", link: "/zh/conditions/has_item" },
        { text: "has_item_data", link: "/zh/conditions/has_item_data" },
        { text: "has_job_level", link: "/zh/conditions/has_job_level" },
        { text: "has_lands_role", link: "/zh/conditions/has_lands_role" },
        { text: "has_mana", link: "/zh/conditions/has_mana" },
        {
          text: "has_mcmmo_level",
          link: "/zh/conditions/has_mcmmo_level",
        },
        { text: "has_permission", link: "/zh/conditions/has_permission" },
        { text: "has_pet", link: "/zh/conditions/has_pet" },
        { text: "has_pet_level", link: "/zh/conditions/has_pet_level" },
        {
          text: "has_potion_effect",
          link: "/zh/conditions/has_potion_effect",
        },
        {
          text: "has_premium_battlepass",
          link: "/zh/conditions/has_premium_battlepass",
        },
        {
          text: "has_quest_active",
          link: "/zh/conditions/has_quest_active",
        },
        { text: "has_reforge", link: "/zh/conditions/has_reforge" },
        {
          text: "has_scoreboard_visible",
          link: "/zh/conditions/has_scoreboard_visible",
        },
        { text: "has_scroll", link: "/zh/conditions/has_scroll" },
        {
          text: "has_skill_level",
          link: "/zh/conditions/has_skill_level",
        },
        { text: "has_talisman", link: "/zh/conditions/has_talisman" },
        { text: "has_town_role", link: "/zh/conditions/has_town_role" },
        { text: "in_air", link: "/zh/conditions/in_air" },
        { text: "in_biome", link: "/zh/conditions/in_biome" },
        { text: "in_block", link: "/zh/conditions/in_block" },
        { text: "in_bubble", link: "/zh/conditions/in_bubble" },
        {
          text: "in_edprison_gang",
          link: "/zh/conditions/in_edprison_gang",
        },
        { text: "in_gamemode", link: "/zh/conditions/in_gamemode" },
        { text: "in_lava", link: "/zh/conditions/in_lava" },
        { text: "in_mainhand", link: "/zh/conditions/in_mainhand" },
        { text: "in_offhand", link: "/zh/conditions/in_offhand" },
        { text: "in_own_claim", link: "/zh/conditions/in_own_claim" },
        { text: "in_rain", link: "/zh/conditions/in_rain" },
        { text: "in_region", link: "/zh/conditions/in_region" },
        { text: "in_slot", link: "/zh/conditions/in_slot" },
        {
          text: "in_trusted_claim",
          link: "/zh/conditions/in_trusted_claim",
        },
        { text: "in_water", link: "/zh/conditions/in_water" },
        { text: "in_world", link: "/zh/conditions/in_world" },
        { text: "is_alive", link: "/zh/conditions/is_alive" },
        {
          text: "is_booster_active",
          link: "/zh/conditions/is_booster_active",
        },
        {
          text: "is_expression_true",
          link: "/zh/conditions/is_expression_true",
        },
        { text: "is_falling", link: "/zh/conditions/is_falling" },
        { text: "is_flying", link: "/zh/conditions/is_flying" },
        { text: "is_frozen", link: "/zh/conditions/is_frozen" },
        { text: "is_gliding", link: "/zh/conditions/is_gliding" },
        { text: "is_night", link: "/zh/conditions/is_night" },
        { text: "is_op", link: "/zh/conditions/is_op" },
        { text: "is_season", link: "/zh/conditions/is_season" },
        { text: "is_sneaking", link: "/zh/conditions/is_sneaking" },
        { text: "is_sprinting", link: "/zh/conditions/is_sprinting" },
        { text: "is_storm", link: "/zh/conditions/is_storm" },
        { text: "is_submerged", link: "/zh/conditions/is_submerged" },
        { text: "is_swimming", link: "/zh/conditions/is_swimming" },
        { text: "is_wearing_set", link: "/zh/conditions/is_wearing_set" },
        {
          text: "item_data_equals",
          link: "/zh/conditions/item_data_equals",
        },
        {
          text: "item_level_above",
          link: "/zh/conditions/item_level_above",
        },
        {
          text: "item_level_below",
          link: "/zh/conditions/item_level_below",
        },
        {
          text: "item_level_equals",
          link: "/zh/conditions/item_level_equals",
        },
        {
          text: "item_points_above",
          link: "/zh/conditions/item_points_above",
        },
        {
          text: "item_points_below",
          link: "/zh/conditions/item_points_below",
        },
        {
          text: "item_points_equal",
          link: "/zh/conditions/item_points_equal",
        },
        {
          text: "lands_balance_above",
          link: "/zh/conditions/lands_balance_above",
        },
        {
          text: "lands_balance_below",
          link: "/zh/conditions/lands_balance_below",
        },
        {
          text: "lands_balance_equal",
          link: "/zh/conditions/lands_balance_equal",
        },
        {
          text: "light_level_below",
          link: "/zh/conditions/light_level_below",
        },
        {
          text: "mcmmo_ability_on_cooldown",
          link: "/zh/conditions/mcmmo_ability_on_cooldown",
        },
        { text: "near_entity", link: "/zh/conditions/near_entity" },
        { text: "on_fire", link: "/zh/conditions/on_fire" },
        { text: "on_ground", link: "/zh/conditions/on_ground" },
        {
          text: "placeholder_contains",
          link: "/zh/conditions/placeholder_contains",
        },
        {
          text: "placeholder_equals",
          link: "/zh/conditions/placeholder_equals",
        },
        {
          text: "placeholder_greater_than",
          link: "/zh/conditions/placeholder_greater_than",
        },
        {
          text: "placeholder_less_than",
          link: "/zh/conditions/placeholder_less_than",
        },
        { text: "points_equal", link: "/zh/conditions/points_equal" },
        { text: "riding_entity", link: "/zh/conditions/riding_entity" },
        {
          text: "standing_on_block",
          link: "/zh/conditions/standing_on_block",
        },
        { text: "stat_above", link: "/zh/conditions/stat_above" },
        { text: "stat_below", link: "/zh/conditions/stat_below" },
        { text: "stat_equals", link: "/zh/conditions/stat_equals" },
        { text: "wearing_boots", link: "/zh/conditions/wearing_boots" },
        {
          text: "wearing_chestplate",
          link: "/zh/conditions/wearing_chestplate",
        },
        { text: "wearing_helmet", link: "/zh/conditions/wearing_helmet" },
        {
          text: "wearing_leggings",
          link: "/zh/conditions/wearing_leggings",
        },
        {
          text: "within_radius_of",
          link: "/zh/conditions/within_radius_of",
        },
      ],
    },
  ],
  '/zh/mutators/': [
    {
      text: "Mutators 变异器",
      items: [
        { text: "所有变异器（导航页）", link: "/zh/mutators/" },
        {
          text: "block_to_location",
          link: "/zh/mutators/block_to_location",
        },
        {
          text: "dispatcher_as_player",
          link: "/zh/mutators/dispatcher_as_player",
        },
        {
          text: "dispatcher_as_victim",
          link: "/zh/mutators/dispatcher_as_victim",
        },
        {
          text: "location_to_block",
          link: "/zh/mutators/location_to_block",
        },
        {
          text: "location_to_cursor",
          link: "/zh/mutators/location_to_cursor",
        },
        {
          text: "location_to_drop",
          link: "/zh/mutators/location_to_drop",
        },
        {
          text: "location_to_player",
          link: "/zh/mutators/location_to_player",
        },
        {
          text: "location_to_projectile",
          link: "/zh/mutators/location_to_projectile",
        },
        {
          text: "location_to_victim",
          link: "/zh/mutators/location_to_victim",
        },
        {
          text: "player_as_victim",
          link: "/zh/mutators/player_as_victim",
        },
        { text: "player_to_pet", link: "/zh/mutators/player_to_pet" },
        { text: "spin_location", link: "/zh/mutators/spin_location" },
        { text: "spin_velocity", link: "/zh/mutators/spin_velocity" },
        {
          text: "translate_location",
          link: "/zh/mutators/translate_location",
        },
        {
          text: "victim_as_dispatcher",
          link: "/zh/mutators/victim_as_dispatcher",
        },
        {
          text: "victim_as_player",
          link: "/zh/mutators/victim_as_player",
        },
        { text: "victim_to_owner", link: "/zh/mutators/victim_to_owner" },
      ],
    },
  ],
  '/zh/examples/': [
    {
      text: "示例",
      items: [{ text: "示例与最佳实践", link: "/zh/examples/" }],
    },
  ],
};
